Repository scania/scania-theme, pull requests merged in 2019-12, with the labels that each got.

#93 Update readme for beta.4 release
  README.md
Labels: improvement

#91 bump version
  package.json
Labels: improvement

#96 Fix z-index on navigation
  src/styles/elements/c-navigation.scss
Labels: Bug

#97 Fix gray background in IE
  src/styles/elements/c-navigation.scss
Labels: Bug

#98 Templates updated
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/improvement-request.md
  PULL_REQUEST_TEMPLATE.md
Labels: Improvement

#99 Bumped version to alpha.24
  README.md
  package.json
Labels: Improvement

#104 Bug- Dropdown split button padding changed
  package-lock.json
  src/styles/components/_dropdowns.scss
Labels: Bug

#103 Bug - Fixed root data url for CDN
  gulpfile.babel.js
  src/styles/elements/c-footer.scss
  src/styles/elements/c-header.scss
Labels: Bug

#105 Remove corporate-ui-dev
  README.md
Labels: Improvement

#106 Bumped to version 1.0.0
  package-lock.json
  package.json
Labels: Improvement

#108 Added badge in the readme for github actions
  README.md
Labels: Improvement

#110 Fix bug in footer: on IE it adds white block
  src/styles/elements/c-footer.scss
Labels: Bug

#109 Added fix for css vars being rendered by stencil in IE
  src/styles/elements/c-content.scss
  src/styles/elements/c-footer.scss
  src/styles/elements/c-global-style.scss
  src/styles/elements/c-header.scss
  src/styles/elements/c-navigation.scss
  src/styles/elements/c-theme.scss
Labels: Bug

#111 Improvement/bump version
  package-lock.json
  package.json
Labels: Improvement
