Repository scania/scania-theme, pull requests merged in 2019-09, with the labels that each got.

#13 Improvement/restructuring of components
  gulpfile.babel.js
  package.json
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/styles/components/_alert.scss
  src/styles/components/_button.scss
  src/styles/components/_table.scss
  src/styles/components/c-global-style.scss
  src/styles/elements/c-card.scss
  src/styles/elements/c-content.scss
  src/styles/elements/c-footer.scss
  src/styles/elements/c-global-style.scss
  src/styles/elements/c-header.scss
  src/styles/elements/c-icon.scss
  src/styles/elements/c-navigation.scss
  src/styles/elements/c-theme.scss
Labels: improvement

#38 Improve release flow
  package.json
Labels: improvement

#23 Improvement for navigation - remove margin padding
  src/styles/elements/c-content.scss
  src/styles/elements/c-navigation.scss
Labels: improvement

#39 Bumped version
  package.json
Labels: improvement

#40 Improved release flow
  package.json
Labels: improvement

#21 Modal styling first draft - based on 3.5.x
  src/styles/_variables.scss
  src/styles/components/_modal.scss
  src/styles/elements/c-global-style.scss
Labels: feature

#42 Button-group styling first draft - Based on ux-pin
  src/styles/components/_button-group.scss
  src/styles/elements/c-global-style.scss
Labels: feature

#22 Dropdown styling first draft - based on 3.5.x
  src/styles/components/_dropdowns.scss
  src/styles/elements/c-global-style.scss
Labels: feature

#43 Initial styling for form
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/styles/components/_forms.scss
  src/styles/components/_table.scss
  src/styles/elements/c-global-style.scss
  src/styles/elements/c-theme.scss
Labels: feature

#47 Added a new typograhpy file and fixed color for headline
  src/styles/_variables.scss
  src/styles/elements/c-global-style.scss
  src/styles/elements/c-theme.scss
  src/styles/utilities/typography.scss
Labels: bug

#45 Added root colors in IE theme
  gulpfile.babel.js
Labels: bug

#48 Bumped version from 17 to 18
  README.md
  package.json
Labels: feature

#49 Update readme with correct corporate ui version
  README.md
Labels: improvement

#25 Badge styling first draft - based on ux-pin
  src/styles/components/_badges.scss
  src/styles/elements/c-global-style.scss
Labels: feature

#28 Progressbar styling first draft - Based on ux-pin
  src/styles/components/_progressbars.scss
  src/styles/elements/c-global-style.scss
Labels: feature

#50 Improvement - input group initial style
  src/styles/_variables.scss
  src/styles/components/_dropdowns.scss
  src/styles/components/_forms.scss
  src/styles/components/_input-group.scss
  src/styles/elements/c-global-style.scss
Labels: improvement

#53 Added navs initial style
  src/styles/_variables.scss
  src/styles/components/_navs.scss
  src/styles/elements/c-global-style.scss
  src/styles/elements/c-navigation.scss
  src/styles/utilities/typography.scss
Labels: feature

#35 List-group styling first draft - Based on 3.5.x
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/styles/components/_list-group.scss
  src/styles/elements/c-global-style.scss
Labels: feature
