Repository scania/scania-theme, pull requests merged in 2019-11, with the labels that each got.

#80 Fix alert function not mapping to color
  src/styles/elements/c-global-style.scss
Labels: bug

#81 Fix incorrect placement caret for Select in Internet Explorer
  src/styles/components/_forms.scss
Labels: bug

#83 Bump version in package.json
  package.json
Labels: improvement

#85 Fixed css for buttons rendered twice
  src/styles/components/_button-group.scss
  src/styles/components/_dropdowns.scss
Labels: bug

#82 Refactor theme structure
  gulpfile.babel.js
Labels: improvement

#88 Bumped version
  package.json
Labels: feature

#87 Added sourcemapping for component
  gulpfile.babel.js
Labels: improvement

#60 Added a default display type for components
  src/styles/elements/c-content.scss
  src/styles/elements/c-footer.scss
  src/styles/elements/c-header.scss
  src/styles/elements/c-navigation.scss
Labels: improvement

#90 Updated dependencies and added github actions initial flow
  .github/workflows/nodejs.yml
  .gitignore
  package-lock.json
  package.json
Labels: bug

#89 Remove underline from dealer header title
  src/styles/elements/c-header.scss
Labels: bug
