Repository scania/scania-theme, pull requests merged in 2019-10, with the labels that each got.

#30 Pagination styling first draft - Based on 3.5.x
  src/styles/_variables.scss
  src/styles/components/_pagination.scss
  src/styles/elements/c-global-style.scss
Labels: feature

#24 Breadcrumbs styling first draft - based on 3.5.x
  src/styles/components/_breadcrumbs.scss
  src/styles/elements/c-global-style.scss
Labels: feature

#54 Added colors for data-env styling
  src/styles/_mixins.scss
  src/styles/elements/c-global-style.scss
  src/styles/utilities/data-env.scss
Labels: feature

#55 Added loading styles
  src/styles/elements/c-global-style.scss
  src/styles/utilities/loading.scss
Labels: feature

#56 Add intial Card styling
  src/styles/components/_cards.scss
  src/styles/elements/c-global-style.scss
Labels: feature

#51 Added active class style for subnavigation
  src/styles/elements/c-navigation.scss
  src/styles/utilities/typography.scss
Labels: improvement

#57 Bump the version number
  package.json
Labels: improvement

#69 improvement - table thead border color matching
  src/styles/_variables.scss
  src/styles/components/_table.scss
Labels: improvement

#67 Typograhpy updated new body color and font for headlines
  src/styles/_variables.scss
  src/styles/components/_badges.scss
  src/styles/components/_breadcrumbs.scss
  src/styles/components/_forms.scss
  src/styles/components/_list-group.scss
  src/styles/elements/c-theme.scss
  src/styles/utilities/typography.scss
Labels: improvement

#65 Fix gray background color in slotted div
  src/styles/elements/c-navigation.scss
Labels: bug

#71 Active colors for links and social-media added in c-footer
  src/styles/_variables.scss
  src/styles/components/_navs.scss
  src/styles/elements/c-footer.scss
  src/styles/elements/c-global-style.scss
Labels: improvement

#72 Add dealer header
  src/images/logotype.svg
  src/styles/elements/c-dealer-header.scss
  src/styles/elements/c-header.scss
Labels: feature

#68 Added more styling to form
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/styles/components/_custom-forms.scss
  src/styles/components/_forms.scss
  src/styles/elements/c-global-style.scss
  src/styles/utilities/typography.scss
Labels: improvement

#76 Bumped version to 1.0.0-alpha.20
  package.json
Labels: feature

#78 Added release badge
  README.md
Labels: improvement

#79 Fix sticky navigation z-index
  src/styles/elements/c-navigation.scss
Labels: bug

#77 Add new script command in package.json
  package.json
Labels: improvement
