Repository scania/scania-theme, pull requests merged in 2020-01, with the labels that each got.

#112 Fix for incorrect colors in IE
  src/styles/_mixins.scss
  src/styles/components/_button.scss
  src/styles/components/_custom-forms.scss
  src/styles/components/_forms.scss
  src/styles/components/_input-group.scss
  src/styles/components/_table.scss
  src/styles/elements/c-global-style.scss
  src/styles/utilities/typography.scss
Labels: Bug

#113 Refactored FOUC part
  src/styles/elements/c-content.scss
  src/styles/elements/c-footer.scss
  src/styles/elements/c-header.scss
  src/styles/elements/c-navigation.scss
Labels: Improvement

#115 Feature - Bump version for pre release theme
  package-lock.json
  package.json
Labels: Feature

#117 Bump version
  package-lock.json
  package.json
Labels: Feature

#119 Add script for pre-release with tag next and bump version
  package-lock.json
  package.json
Labels: Improvement
